name: Terraform plan
description: Plan the Terraform script and (optionally) upload the resulting artifact
inputs:
  output-path:
    description: Path where to store the resulting output plan
    required: false
    default: output
  upload-artifact:
    description: Set to true to upload the resulting artifact with the TF plan
    required: false
    default: false

runs:
  using: "composite"
  steps:

    - name: Validate
      shell: bash
      run: terraform validate

    - name: Plan
      shell: bash
      run: |
        export TF_VAR_created_by_ci="$CI"
        export TF_VAR_github_repo_name="$GITHUB_REPOSITORY"
        terraform plan \
          -out ${{ inputs.output-path }}

    - if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: plan_output
        if-no-files-found: error
        path: ${{ inputs.output-path }}
